/*
create a class Address to store street, city ,state and pin number
create a class Person to store id, name, and object of address class
In person class id should be autogenerated (Hint: use static int count to assign id)
class Address{
   char * street;
   char* city;
   char* state;
   int pin;
}

class Person{
   int id;
   char *name;
   Address addr;    //object of address class (HAS-A relationship)
}

create Array of pointers to store Person objects
and write code for following
	1. Add new Person
        2. Display All Person
        3. Search by Id
        5. Search by Name
        6. Modify address;
	7. find address by id of Person
	8. display all Person stay in given city------>(accept city from user)
        9. Exit
*/

#pragma once

class Address {
	char* street;
	char* city;
	char* state;
	int pin;
	
	public:
		Address();
		Address(const char* str, const char* ct, const char* stt, int pin);
		virtual ~Address();
		
		// setters
		void setStreet(const char* str);
		void setCity(const char* ct);
		void setState(const char* stt);
		void setPin(int pin);
		
		// getters
		const char* getStreet();
		const char* getCity();
		const char* getState();
		int getPin();
		
		virtual void display();
};